"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

const contentFr = {
  tagline: "Outils et guides pour investir de maniere conforme a la charia. Donnees ouvertes, transparentes, gratuites.",
  indices: "Indices",
  methodologyHref: "/methodologie",
  methodologyLabel: "Methodologie",
  guidesTitle: "Guides",
  allGuidesHref: "/guides",
  allGuidesLabel: "Tous les guides",
  whyInvestHref: "/guides/pourquoi-investir",
  whyInvestLabel: "Pourquoi investir ?",
  halalStocksHref: "/guides/actions-boursieres",
  halalStocksLabel: "Actions boursieres",
  disclaimerLabel: "Avertissement important :",
  disclaimer: "Les informations presentees sur ce site sont generees automatiquement par scraping de sources publiques (SlickCharts, Zoya.finance) et ne constituent en aucun cas un conseil en investissement, un conseil financier ou un avis religieux. Les donnees peuvent contenir des erreurs. Le statut halal/haram est fourni a titre indicatif uniquement — faites vos propres recherches et consultez un conseiller financier qualifie ainsi qu'un scholar islamique avant toute decision d'investissement. Les createurs de ce site declinent toute responsabilite quant a l'exactitude des donnees et aux decisions prises sur cette base.",
  bottomLine: "MuslimFinance.net — Donnees ouvertes, pas de conseil financier",
  nasdaqHref: "/nasdaq-halal",
  sp500Href: "/sp500-halal",
};

const contentEn = {
  tagline: "Tools and guides for Shariah-compliant investing. Open data, transparent, free.",
  indices: "Indices",
  methodologyHref: "/en/methodology",
  methodologyLabel: "Methodology",
  guidesTitle: "Resources",
  allGuidesHref: "/en",
  allGuidesLabel: "Home",
  whyInvestHref: "/en/nasdaq-halal",
  whyInvestLabel: "NASDAQ 100 Halal",
  halalStocksHref: "/en/sp500-halal",
  halalStocksLabel: "S&P 500 Halal",
  disclaimerLabel: "Important disclaimer:",
  disclaimer: "The information on this site is automatically generated by scraping public sources (SlickCharts, Zoya.finance) and does not constitute investment advice, financial advice, or religious guidance in any way. Data may contain errors. Halal/haram status is provided for informational purposes only — do your own research and consult a qualified financial advisor and an Islamic scholar before making any investment decision. The creators of this site accept no liability for the accuracy of the data or decisions made based on it.",
  bottomLine: "MuslimFinance.net — Open data, not financial advice",
  nasdaqHref: "/en/nasdaq-halal",
  sp500Href: "/en/sp500-halal",
};

export function Footer() {
  const pathname = usePathname();
  const isEn = pathname === "/en" || pathname.startsWith("/en/");
  const t = isEn ? contentEn : contentFr;

  return (
    <footer className="border-t border-[var(--border)] bg-white">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="grid gap-8 md:grid-cols-3">
          <div>
            <div className="flex items-center gap-2.5 mb-4">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[var(--color-navy)]">
                <span className="text-sm font-bold text-white">MF</span>
              </div>
              <span className="text-lg font-bold tracking-tight text-[var(--color-navy)]">
                Muslim<span className="text-[var(--color-gold)]">Finance</span>
              </span>
            </div>
            <p className="text-sm text-[var(--color-muted-foreground)] leading-relaxed">
              {t.tagline}
            </p>
          </div>
          <div>
            <h3 className="mb-3 text-sm font-semibold text-[var(--color-navy)]">{t.indices}</h3>
            <div className="flex flex-col gap-2">
              <Link href={t.nasdaqHref} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                NASDAQ 100 Halal
              </Link>
              <Link href={t.sp500Href} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                S&P 500 Halal
              </Link>
              <Link href={t.methodologyHref} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                {t.methodologyLabel}
              </Link>
            </div>
          </div>
          <div>
            <h3 className="mb-3 text-sm font-semibold text-[var(--color-navy)]">{t.guidesTitle}</h3>
            <div className="flex flex-col gap-2">
              <Link href={t.allGuidesHref} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                {t.allGuidesLabel}
              </Link>
              <Link href={t.whyInvestHref} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                {t.whyInvestLabel}
              </Link>
              <Link href={t.halalStocksHref} className="cursor-pointer text-sm text-[var(--color-muted-foreground)] hover:text-[var(--color-navy)] transition-colors duration-200">
                {t.halalStocksLabel}
              </Link>
            </div>
          </div>
        </div>
        <div className="mt-10 border-t border-[var(--border)] pt-6">
          <div className="rounded-xl border border-[var(--color-haram)]/20 bg-[var(--color-haram-muted)] p-4 mb-6">
            <p className="text-xs text-[var(--color-muted-foreground)] leading-relaxed">
              <strong className="text-[var(--foreground)]">{t.disclaimerLabel}</strong>{" "}
              {t.disclaimer}
            </p>
          </div>
          <p className="text-center text-xs text-[var(--color-muted-foreground)]">
            {t.bottomLine}
          </p>
        </div>
      </div>
    </footer>
  );
}
